[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
	"crt0stack",
	"enarx-keep-sev",
	"enarx-keep-sev-shim",
	"enarx-keep-sgx",
	"enarx-keep-sgx-shim",
	"enumerate",
	"intel-types",
	"iocuddle",
	"iocuddle-sgx",
	"keep-runtime",
	"memory",
	"payload",
	"sallyport",
	"sev",
	"sev-show",
	"sevctl",
	"sgx-crypto",
	"sgx-show",
	"sgx-types",
	"span",
	"testing",
	"tests",
	"units",
	"vdso"
]
CARGO_WORKSPACE_ROOT = { script = ["git rev-parse --show-toplevel"] }

[tasks.deny]
install_crate = "cargo-deny"
command = "cargo"
args = ["deny", "check", "licenses"]

[tasks.misc-lints-missing-docs]
command = "${CARGO_WORKSPACE_ROOT}/.tests/misc-lints-missing-docs"

[tasks.cargo-toml-package-edition]
install_script = [''' which toml || cargo install toml-cli ''']
command = "${CARGO_WORKSPACE_ROOT}/.tests/cargo-toml-package-edition"

[tasks.misc-lints-clippy-all]
command = "${CARGO_WORKSPACE_ROOT}/.tests/misc-lints-clippy-all"

[tasks.misc-licenses-rs-spdx]
command = "${CARGO_WORKSPACE_ROOT}/.tests/misc-licenses-rs-spdx"

[tasks.misc-licenses-asm-spdx]
command = "${CARGO_WORKSPACE_ROOT}/.tests/misc-licenses-asm-spdx"

[tasks.misc-diagrams]
workspace = false
# This is the only non-crate-level task. To prevent the pre-ci-flow
# from spuriously triggering this *inside* member crates, let's just
# detect whether we're in a crate directory and if we are, this test
# will be skipped. It doesn't make sense to run inside a crate directory.
condition = { env_not_set = ["CARGO_MAKE_CRATE_NAME"]}
command = "${CARGO_WORKSPACE_ROOT}/.tests/misc-diagrams"

[tasks.cargo-toml-package-license]
command = "${CARGO_WORKSPACE_ROOT}/.tests/cargo-toml-package-license"

[tasks.misc-licenses-crate]
command = "${CARGO_WORKSPACE_ROOT}/.tests/misc-licenses-crate"

# This will run first fmt + build for each crate and then test for each crate.
[tasks.test]
clear = true
workspace = false
run_task = { name = ["fmtbuild", "test-inner"], fork = true }

# Runs format and build (used before testing).
[tasks.fmtbuild]
dependencies = ["format", "build"]

# Copy of "test" under a different name to avoid circular dependency.
[tasks.test-inner]
description = "Runs all available tests."
category = "Test"
command = "cargo"
args = ["test", "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)", "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )"]

# Add additional tests to the predefined 'ci-flow' target.
[tasks.pre-ci-flow]
dependencies = [
	"cargo-toml-package-edition",
	"cargo-toml-package-license",
	"check-format",
	"deny",
	"misc-diagrams",
	"misc-licenses-asm-spdx",
	"misc-licenses-crate",
	"misc-licenses-rs-spdx",
	"misc-lints-clippy-all",
	"misc-lints-missing-docs",
]

# Overwrites ci-flow task to ensure tests are run last in ci-flow.
[tasks.ci-flow]
clear = true
workspace = false
run_task = { name = ["ci-flow-mod", "test-inner"], fork = true }

# Removes test-flow from ci-flow in order to ensure build dependencies are met
# during testing.
[tasks.ci-flow-mod]
description = "CI task will run cargo build and cargo test with verbose output"
category = "CI"
dependencies = [
    "pre-ci-flow",
    "print-env-flow",
    "pre-build",
    "check-format-ci-flow",
    "clippy-ci-flow",
    "build",
    "post-build",
    "examples-ci-flow",
    "bench-ci-flow",
    "outdated-ci-flow",
    "ci-coverage-flow",
    "post-ci-flow"
]
